vars: {
  d2-config: {
    theme-id: 1
    layout-engine: elk
  }
}

shape: sequence_diagram

browser -> server: richiesta GET

server -> browser: risposta HTML (dom minimo)
server -> browser: risposta JS
server -> browser: risposta assets
